### ISSUE TITLE
Downloading submissions

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#102]
Currently you can only download one submission. We'd like a feature to download multiple submissions(and if so, there should be their ID somewhere because they tend to forget to sign their source files with their names) and to download the last submission of each user to an assignment(manually downloading the last submission for each student would be a pain if we wanted to run moss on their homeworks)

**Comment by mgax** [comment]
You can already download the last submission for each user on a given assignment (though it currently throws an error, whoops :) https://github.com/vmck/acs-interface/issues/104). Does that feature do what you need?

<img width="539" alt="Screenshot 2019-11-04 at 11 26 03" src="https://user-images.githubusercontent.com/27617/68110934-9d8a3080-fef6-11e9-849c-3591a16096d4.png">

**Comment by Mr-Vinti** [comment]
Yes, that's great, didn't see that option before.

**Comment by mgax** [comment]
@Mr-Vinti Does this work for you now? Can we close the issue?

**Comment by Mr-Vinti** [comment]
Yes, it worked perfectly ^_^
