### ISSUE TITLE
Vagrant Provisioning Fail

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#114]
Vagrant fails to provision with the following error:
```
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20191114-8816-1c1k12z.sh
    default: + sudo docker cp cluster:/app/bin/nomad /usr/local/bin/nomad
    default: Error: No such container:path: cluster:/app/bin/nomad
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by mgax** [comment]
Right, so this is actually a re-run of the provisioning, after the initial run failed. The first run probably got stuck [here](https://github.com/vmck/acs-interface/blob/master/ci/provision-cluster.sh#L17). A workaround is:

```shell
vagrant ssh -- rm -rf /opt/cluster
vagrant provision
```

So that it provisions the cluster again from the start.

**Comment by mgax** [comment]
We could run the provision scripts as root by removing `privileged: false` from the lines in Vagrantfile. The scripts will probably need tweaking.

https://github.com/vmck/acs-interface/blob/85cf502103407f72833a8933075fab285e679d97/Vagrantfile#L13-L16
