### ISSUE TITLE
Have a separation between different courses

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#119]
Have a separation between course assignments.
Ex: To upload assignment for a PC homework you will need to click on PC and then select the homework

**Comment by gmuraru** [comment]
For further reading: https://stackoverflow.com/a/12354293

**Comment by gmuraru** [comment]
@mgax don't close this issue yet. I want to write a separate file with what features are now in vmcheckerv2

**Comment by mgax** [comment]
> I want to write a separate file with what features are now in vmcheckerv2

Then why not make an issue for that? Or change this issue's title and description. I realise it means "write documentation" to you, but not to anybody else, sorry :)

And, if it's all the same to you, I suggest you do the writeup on this repo's wiki, so it's easy to update and to link.

**Comment by Jokeswar** [comment]
@gmuraru is it alright if we close this? We have the wiki for the features, don't we?

**Comment by gmuraru** [comment]
Yes, we have.
