### ISSUE TITLE
Use cache proxy for packages

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#120]
Currently if we want to use a package that is not in a virtual machine we need to install it from the ```checker.sh``` script.

This might cause problems when there are sent a lot of request - we need to use a cache proxy for this.

**Comment by mgax** [comment]
The checker VMs currently run with no internet access, so they can't talk to any package repository. We would have to start qemu with extra arguments (`guestfwd=` with netcat, perhaps). Moving to backlog for now.

**Comment by gmuraru** [comment]
@mgax I think we can close this since the user should add to the docker image all the dependencies, right?

**Comment by mgax** [comment]
Ok sure.
