### ISSUE TITLE
apt-get update not running in check script

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#124]
Can not install packages using ```apt-get install <package>```

**Comment by Jokeswar** [comment]
A VM started **without** the submission manager, but with the same options and image is able to use `apt-get update` and `apt-get install`.

**Comment by mgax** [comment]
From slack: the VMs for submissions have restricted network, therefore they can't access the dpkg mirror.

**Comment by gmuraru** [comment]
So this is working as expected - also having ```apt-get``` would be a security issue with the vm. I think I will close this.
