### ISSUE TITLE
Have MOSS integrated

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#140]
[MOSS](https://theory.stanford.edu/~aiken/moss/) is a tool used for plagiarism detection - a second opinion need to be given by a human.

Integrate MOSS into vmchecker2.
Update documents on how to use it.

**Comment by gmuraru** [comment]
@Jokeswar you took this issue, right?

**Comment by Jokeswar** [comment]
@gmuraru yes. I forgot to assign myself.

**Comment by gmuraru** [comment]
@Jokeswar could you also document it?
https://github.com/vmck/acs-interface/wiki/Features

**Comment by Jokeswar** [comment]
@gmuraru done! Can you take a look and give me a heads up if anything seems off?
