### ISSUE TITLE
Review pop-up

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#15]
TA clicks a button on a submission report, a textarea opens, and they type in vmchecker style grading.

**Comment by mgax** [comment]
@murarugeorgec could you please provide an example of vmr grading for us?

**Comment by murarugeorgec** [comment]
Sure. It looks something like this:
```
-1.0: Indentare neconsecventa
-2.5: Functii si variabile cu nume nesugestive
    Ex: a, b, functie1
```
Cateodata lumea mai trece la finalul fisierului cine si cand a corectat. Ex
```
George Muraru, 17.01.2018
```
Exemplul este creat pe moment - insa asa arata un fisier vmr grade.
Initial (inainte de corectare) acesta are in el textul ```ok```
