### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#16]
Run a bunch of old submissions from the PC course to see how the system performs under load.

**Comment by murarugeorgec** [comment]
Uploaded the assignments on the ```so``` course elf, under the folder ```/home/so/people/george.muraru/pc-cb```

**Comment by mgax** [comment]
There's a zip file with a bunch of zero-sized zip files inside. Please try again :)

**Comment by murarugeorgec** [comment]
I sent it to you @mgax on the slack channel. Hope I did not mess it up again.

**Comment by mgax** [comment]
I've copied it to the server on fep, waiting the app to be set up, so we can stress the hell out of it.

**Comment by Jokeswar** [comment]
The results after running 239 submissions on `fritz`:
* Time taken to complete all submissions: **aprox. 40 minutes**
* Submissions run in parallel: **aprox. 15**
* Time per submission: **aprox. 1 minute**

Drawbacks:
* SQlite throws `database locked` errors on botg `vmck` and `acs-interface`, and submission results are not saved
* After the first 40-50 submissions, acs-interface slows down to 1 submission sent to vmck every 7 seconds from 1 submission per second

**Comment by murarugeorgec** [comment]
Could we catch that exception and ```freeze``` the submit button until the load of the system is smaller?

**Comment by mgax** [comment]
> Could we catch that exception and `freeze` the submit button until the load of the system is smaller?

Nah, that's counter-productive. There's no good reason for the front-end to become unresponsive. And the submissions received get queued, so they won't degrade performance of the evaluations.

**Comment by murarugeorgec** [comment]
"SQlite throws database locked errors on botg vmck and acs-interface, and submission results are not saved" @Jokeswar when you say this, it means that a student might have uploaded his homework but it will not get a result, right?

**Comment by mgax** [comment]
> it means that a student might have uploaded his homework but it will not get a result, right?

Not quite. It means the student will get web page errors when interacting with the UI (but they can click refresh like any normal facebook user) and that submission checker jobs may fail (but they get flagged and we can easily reschedule them).

Also, we should https://github.com/vmck/acs-interface/issues/34 :)

**Comment by murarugeorgec** [comment]
Ok, then I think we could close this one and reopen a new one when we have the #34 done.
Or keep it open until #34 is done and retest it?

**Comment by mgax** [comment]
We're still validating the prod environment, now with a new node - https://github.com/vmck/acs-deploy/issues/10 - let's keep the issue open until we're satisfied the deployment will hold under load.

**Comment by mgax** [comment]
Can we also migrate data? Should be straightforward: https://gist.github.com/sirodoht/f598d14e9644e2d3909629a41e3522ad

**Comment by mgax** [comment]
Are we happy with the stress test? What problems do we expect when a bunch of students start hitting the system?

**Comment by mgax** [comment]
> Are we happy with the stress test? What problems do we expect when a bunch of students start hitting the system?

ping @Jokeswar :)

**Comment by Jokeswar** [comment]
In the unlikely event that something weird happens to `vmck`, and it triggers a `template re-render` we might loose the results for 3 or 4 submissions. `Acs-interface` will take a bit of time to respond to requests, if they target `/submission` because polling `vmck` is still a bit costly.

**Comment by Jokeswar** [comment]
Also to give you some numbers: submitting 239 archives took ~35 min. Evaluating them ~3h.

**Comment by mgax** [comment]
Good enough for us. Thanks for taking the time to test this properly. :+1:
