### ISSUE TITLE
Download homework from the submission list for user

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#171]
Currently, a user can download only the submissions he/she made.

We need to move the "Download submission" possibility from the `/submission/` view (that lists all submissions).

Why should we do this? -- in the `/submission/` view there all the submission for all the users.
An idea will be to move this functionality to the `/assignment/<user>` view

**Comment by mgax** [comment]
Or we could move it to the `/submission/<submission_id>` view, the one that details the actual submission?

**Comment by gmuraru** [comment]
Or that one.
