### ISSUE TITLE
Publish the reviews for all the students at a button click

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#174]
Currently, when a teaching assistant reviews a submission, the student can immediately see the updated grade.

This might create frustration between the students (some might get their homework graded earlier and some others 3-4 days after).

We should be able to gather all the review and publish it when it is collected for all the students

**Comment by gothera** [comment]
i take this one

**Comment by gmuraru** [comment]
> i take this one

I assigned you to #181
