### ISSUE TITLE
Stable connection to LDAP server

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#18]
The production deployment currently connects to LDAP through an SSH port forward, and the SSH dies about twice a day, requiring a manual restart. Let's switch to a more permanent solution.

**Comment by mgax** [comment]
@razvand is it possible to allow connections to the LDAP server from `95.216.72.231` (a Hetzner IP)?

**Comment by razvand** [comment]
Yes, it's possible. There is a bind DN that we can use to access the LDAP server. Credentials are private, ofc and will only be available on the actual setup. I can provide them on a different channel or tell me where to configure them when you make the setup.

**Comment by mgax** [comment]
Deployed on a VM on the FEP grid; this one has direct access to LDAP.
