### ISSUE TITLE
Recompute total score if TAs change the deadline

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#181]
The penalty deadline for submissions should be recomputed, if the deadline changes, without user intervention. Currently if TAs change the deadline they have to select all affected submissions and select the `Recompute score` action.

**Comment by gmuraru** [comment]
@gothera are you still working on this?

**Comment by clovis1122** [comment]
I'll tackle this one!

**Comment by clovis1122** [comment]
Hey @Jokeswar @gmuraru, how do I create a submission?

**Comment by clovis1122** [comment]
I tried from the admin site, but got this error:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/22270042/94996370-61ca7180-0572-11eb-826d-e94c23d30814.png">

I'll see if I can create a student account to test.

**Comment by Jokeswar** [comment]
> I tried from the admin site, but got this error:
> 
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/22270042/94996370-61ca7180-0572-11eb-826d-e94c23d30814.png">
> 
> I'll see if I can create a student account to test.

@clovis1122 On /homepage you have the assignment `Verificari interne` that displays only the button `Results`. That is because the assignment expired. You should go to admin, assignments and select `1-1 Verificari interne`. Change `Deadline hard` to a date in the future. Now if you go to the homepage `Verificari interne` there should be a button `Upload`, click it. You should upload a random zip archive. This way you create a submission.

**Comment by clovis1122** [comment]
Thanks, I've open a PR. I cannot properly label it from Github, can you help me out with that?

**Comment by gmuraru** [comment]
This is closed by [this](https://github.com/vmck/acs-interface/pull/268)
