### ISSUE TITLE
Move regular expression separately

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#22]
This piece of [code](https://github.com/vmck/acs-interface/blob/master/interface/models.py#L117-L125) appears [here](https://github.com/vmck/acs-interface/blob/master/interface/utils.py#L14-L25) too. Move it into a separate function with some better var names.

**Comment by izhuravlev** [comment]
Hey @Jokeswar,
I can do that. Are there any other recommendations on this issue?

**Comment by izhuravlev** [comment]
I have also mentioned, that in function ```evaluate(self)```  from **models.py**  [this](https://github.com/vmck/acs-interface/blob/b98ca09d2146cf08c346ba833a78f3f33f960224/interface/models.py#L117-L125) piece of code is being called right before calling ```vmck_config(self)```, defined in the **utils.py**. ```vmck_config``` function has the same block of code in it - so do we actually need it in the ```evaluate(self)``` function?

**Comment by izhuravlev** [comment]
Okay, I've got the difference and the importance of this piece of code. 
Later in the **models.py** file (line 132), we need the ```config_url``` variable - the result from line 123. 
As I have also mentioned, in **models.py** we need only the URL, while in **utils.py** we need the data - so I believe we have to create 2 separate functions - something like _getConfigUrl_ and _getConfigData_. 
I also propose to create a third function _getUrlBase_ with functionality from **utils.py** lines 14-18 and call it in functions _getConfigUrl_ and _getConfigData_.

**Comment by izhuravlev** [comment]
I will be happy to make any corrections if they are required.
