### ISSUE TITLE
Replace f-strings from logging

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#261]
## Description
The f-strings are lacking logging optimizations and they should be removed in expressions like:
```log.info```

Also, some logging info may also contain strings concatenation and it should be avoided.

## Expected Behavior
Logging should work without having the f-string.

**Comment by ptrstr** [comment]
A bit confused by what is the target. How would this look after the fix? `log.info(f"Login failure for {username}")`

Or is it to remove the `f` prefix?

Sorry for the confusion :/

**Comment by refekt** [comment]
I can help. Do you want to use "".format() instead? or %?

**Comment by gmuraru** [comment]
It should be like the following example:
```
logger.info("%s went %s wrong", 42, 'very')
```
@ptrstr do you wanna take the issue?

**Comment by ptrstr** [comment]
Sure! Was gonna ask if you wanted it to look like C's `printf` and that's exactly what it is :) Thanks!

**Comment by Jokeswar** [comment]
Fixed by #266
