### ISSUE TITLE
Create exceptions and replace all asserts

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#263]
## Description
Currently, we use asserts for things like input/response validation. Those asserts would be compiled out if you want to generate optimized bytecode.

Replace all asserts with custom made ```Exceptions``` (those exceptions should be placed in a single file in our repo).

## Expected Behavior
Have a file with all the custom made exceptions and all asserts replaced with them

**Comment by clovis1122** [comment]
@gmuraru can you elaborate a bit more on this issue?

**Comment by gmuraru** [comment]
Sure!

Currently, we use asserts in the code for verifying different stuff.
The problem is that in production, we might want to compile and have bytecode (and this process removes the asserts).

Because of this, we want to replace all asserts with exceptions

**Comment by clovis1122** [comment]
Ah cool, I can tackle it!

**Comment by gmuraru** [comment]
Assigned you :sunglasses:
