### ISSUE TITLE
Remove f-strings from expressions that are not using variables

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#264]
## Description
Remove the f-strings from expressions that are not using a variable.

## Is your feature request related to a problem?
Flake8 is complaining about it

**Comment by ptrstr** [comment]
Can you assign me to this? I'll make a PR with both this and #261

**Comment by gmuraru** [comment]
Sure, assigned you to it

**Comment by Jokeswar** [comment]
Fixed by #266
