### ISSUE TITLE
Check if valid json before returning the state

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#265]
## Description
If we have a server error in ```vmck``` we might not get back a valid json in [here](https://github.com/vmck/acs-interface/blob/master/interface/backend/submission/evaluator/vmck.py#L67-L69) and we get an exception.

Introduce a new state for a submission, like ```ERR```, which means that there was an error while trying to run the submission.
If the json is not valid, return this new state.

## Expected Behavior
If we have an error on the server-side, we should indicate that in the homework.

**Comment by GuillaumeFalourd** [comment]
Hi @gmuraru , would something like this be enough ?

```def update(submission):
       try: 
           response = requests.get(
                urljoin(
                    settings.VMCK_API_URL, f"jobs/{submission.evaluator_job_id}"
                )
            )
       except requests.exceptions.HTTPError as errh:
            return response.json()["HTTP ERR"]
       except requests.exceptions.ConnectionError as errc:
           return response.json()["CONNECTING ERR"]
       except requests.exceptions.Timeout as errt:
           return response.json()["TIMEOUT ERR"]
       except requests.exceptions.RequestException as err:
          return response.json()["ERR"]
       
       return response.json()["state"]
```

Or did you imagined something different ?

**Comment by gmuraru** [comment]
Hmm...this would not work ```response.json()``` since it has thrown an error.
You should do:
```
  try: 
           response = requests.get(
                urljoin(
                    settings.VMCK_API_URL, f"jobs/{submission.evaluator_job_id}"
                )
            )
       except Exception e:
            return "Err" <-- and here this value should be mapped with a state from Submission

       return response.json()["state"]
```

**Comment by GuillaumeFalourd** [comment]
`return "Err" <-- and here this value should be mapped with a state from Submission`
This new STATE should be mapped here : https://github.com/vmck/acs-interface/blob/3cc73d28a4a7f92cd3dd35b264fbe7e7da3acd07/interface/models.py#L115 ?

**Comment by clovis1122** [comment]
Is this issue available to be worked on?

**Comment by gmuraru** [comment]
@clovis1122 I think @GuillaumeFalourd might want to work on it. If not, you can take it.

**Comment by gmuraru** [comment]
> `return "Err" <-- and here this value should be mapped with a state from Submission`
> 
> Should this new STATE be mapped here ?
> 
> https://github.com/vmck/acs-interface/blob/3cc73d28a4a7f92cd3dd35b264fbe7e7da3acd07/interface/models.py#L115

Yes

**Comment by GuillaumeFalourd** [comment]
Yes, I would like to work on it. I was asking some details to understand how to get there 🙂👍🏼
If you can assign it to me please.

**Comment by gmuraru** [comment]
This is closed by [this](https://github.com/vmck/acs-interface/pull/270)
