### ISSUE TITLE
Flake8 and Black formatter on github actions

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#271]
## Description
Run flake8 and black in github actions too. The configuration for the current CI is found [here](https://github.com/vmck/acs-interface/blob/master/.drone.yml). Lines of interest [1-13](https://github.com/vmck/acs-interface/blob/master/.drone.yml#L1-L13). 

## Is your feature request related to a problem?
External contributors do not have access to our private CI workflow due to security reasons. We would want to have at least the code style checks run automatically before we decide if the PR is valid.

**Comment by gmuraru** [comment]
This is already done
