### ISSUE TITLE
Add context processors in settings

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#274]
## Description
Currently, we use the path ```/media/vmck.png``` when referring to the vmck logo.
Add in the settings the ```'django.template.context_processors.media'``` and use the ```MEDIA_URL``` variable in the homepage.

## Is your feature request related to a problem?
That is the standard way to use the ```MEDIA_URL```

**Comment by Jokeswar** [comment]
We switched to using STATIC_ROOT. This is no longer needed
