### ISSUE TITLE
Add button to hide assignments

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#293]
## Description
The button will be added in the admin.
By default, an assignment will be visible, and when that assignment is finished and corrected the TA will mark it that should not be displayed anymore.

## Is your feature request related to a problem?
Assignments won't pile up on the user interface

**Comment by Lucian-MihaiStan** [comment]
I will take it

**Comment by gmuraru** [comment]
Sorry! This is already fixed.
