### ISSUE TITLE
Suggestive error message for incorrect review syntax

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#297]
## Description
500 Internal Server Error is received when the teaching assistant saves a review with incorrect syntax

## How to Reproduce
1. Go to Assignment Review dialog
2. Try to save the review with a first line beginning with:
-0..0: test
3. See error - 500 Server Error

## Expected Behavior
An error message should be sent back to the teaching assistant telling him that the format for the Review is wrong, instead of receiving a 500 error

**Comment by Lucian-MihaiStan** [comment]
I ll take it
