### ISSUE TITLE
Assignment username

### ISSUE THREAD

**Issue by criscojocaru** [vmck/acs-interface#298]
## Description
When you click on a user from the submitted assignments list, the username that appears is the username of the current user instead of the username that you clicked on.

## How to Reproduce
1. For example, go to https://v2.vmchecker.grid.pub.ro/assignment/8/16/user/dorinel.filip
2. See that the username is not dorinel.filip, but your username.

## Expected Behavior
The username that appears should be the one that you clicked on, not yours.

## Screenshots
![image](https://user-images.githubusercontent.com/40690927/106366821-1faa1480-6347-11eb-89a8-090ea27ee991.png)

**Comment by Lucian-MihaiStan** [comment]
I will take it
