### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#35]
We should be able to search by `name`, `submission id` or `assignment id` in our `submission list` view

**Comment by gmuraru** [comment]
@stefanalex99 are you still working on this?

**Comment by stefanalex99** [comment]
@gmuraru no, you can assign someone else

**Comment by Jokeswar** [comment]
@mgax @gmuraru do we still need this one? It's a search bar for the page with all the submissions. We have the result pages for every assignment where all the users can see their last submission for that specific assignment, and a page where the user can see all of its submissions for an assignment.

**Comment by gmuraru** [comment]
No, I think it is ok how it is now
