### ISSUE TITLE
Port homework from SO course

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#50]
Evaluate the first homework of the [SO course](https://ocw.cs.pub.ro/courses/so): https://ocw.cs.pub.ro/courses/so/teme/tema-1. It's both Windows and Linux but let's tackle Linux first.

**Comment by gmuraru** [comment]
Won't fix! The SO course has a Linux and a Windows component (for the moment). We will need to port both homework and doing this is tedious for the Windows component.
