### ISSUE TITLE
Resubmit homework

### ISSUE THREAD

**Issue by Jokeswar** [vmck/acs-interface#51]
Users should be able to rerun their own submissions.

**Comment by mgax** [comment]
I think we should restrict that functionality to TAs. @murarugeorgec what do you think?

**Comment by murarugeorgec** [comment]
Sorry for the late reply. Yes, it should be a functionality only for TAs.

**Comment by mgax** [comment]
Ah, then it's already implemented in the admin, you can select several submissions and reschedule them.
