### ISSUE TITLE
Delete homework - delete all the submissions

### ISSUE THREAD

**Issue by murarugeorgec** [vmck/acs-interface#58]
Currently if I want to delete a homework I will get notified to also delete the submissions -> I need to click on every submission and delete it.

If I want to delete a homework I should be able to delete it without having to manually delete all submissions.

**Comment by mgax** [comment]
The fix is in PR https://github.com/vmck/acs-interface/pull/81

**Comment by mgax** [comment]
Fixed in https://github.com/vmck/acs-interface/commit/39e37f8459ab48a5694cf1feacb90319280141d4#diff-e1658c827f8d14ec06ffad82c2edd14cL72-R72
