### ISSUE TITLE
Fix guest network restrict

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#60]
With the `restrict_network` flag, the guest VM doesn't answer to SSH connections.

There's a working prototype, the [factory](https://github.com/liquidinvestigations/factory) project, which runs temporary VMs, and it can reliably restrict their network access:

```shell
git clone https://github.com/liquidinvestigations/factory && cd factory
pipenv install
pipenv run ./factory prepare-cloud-image  # downloads an ubuntu cloud image and provisions it, similar to packer
pipenv run ./factory login --restrict-network  # starts the VM and logs in with SSH, similar to vmck + vagrant ssh
```

You can test network access using `curl captive.apple.com` or `apt update`. There's a working factory installation on `acs-quark` in `/opt/factory`.

There's a test setup on `acs-quark` in `/opt/qemu-restrict-network-experiment` with a `./run.sh` script that starts a qemu VM. It exposes ports 22 and 80 on the wireguard interface. When started with `restrict=on` ssh access is broken. Wihtout `restrict=on` it works fine.

Some ideas:
* Figure out why there is no output to the console. Maybe the `imgbuild-acs-pc.qcow2` image is not configured for serial console output. Try it with the factory image (`/opt/factory/images/cloud/disk.img`) too.
* Maybe the `imgbuild-acs-pc.qcow2` VM does not finish booting and `sshd` never starts.

**Comment by Jokeswar** [comment]
After some tests, here is what I found:
* If you forward the ssh port to a `localhost`/`loopback` port, you can ssh into the VM with either `restrict=on` or no `restrict` at all.
* If you forward the ssh port to a `wireguard` port, you can **only** ssh into the VM if you have no `restrict=on`.
* This behavior stays true with either `imgbuild-acs-pc.qcow2` or `disk.img`.
* In all cases `sshd` was up and running.

**Comment by Jokeswar** [comment]
Solved using `socat` by forwarding the traffic from wireguard to the vm.
