### ISSUE TITLE
Make it pretty

### ISSUE THREAD

**Issue by murarugeorgec** [vmck/acs-interface#64]
TAs and students want to have a nicer user interface when uploading the homework.

Since my experience is 0 regarding UI - I can not offer a proper feedback - only that keep it simple :)

**Comment by Mr-Vinti** [comment]
I suggest adding Angular to the project. It makes the UI more easily to customize and the design looks better, with already implemented elements, rather than pure HTML, CSS, JS

**Comment by mgax** [comment]
> I suggest adding Angular to the project.

I think at this stage that would be overkill. We have a handful of views that can easily be rendered as Django templates, and bootstrap is good enough as a UI.

**Comment by mgax** [comment]
https://github.com/vmck/acs-interface/pull/67 addresses some of the ugliness.

**Comment by Mr-Vinti** [comment]
> > I suggest adding Angular to the project.
> 
> I think at this stage that would be overkill. We have a handful of views that can easily be rendered as Django templates, and bootstrap is good enough as a UI.

I could design an angular interface but I'd need info about the webservice calls. If you want me to give it a shot, let me know. I'd also need access to the admin part of a class. I'm a Teaching Assistant for the PC class, which @murarugeorgec can confirm, if needed(I'll need it eventually anyways in order to check the homeworks of my students :)) )

**Comment by mgax** [comment]
> I'd also need access to the admin part of a class.

That's fixed.

> I could design an angular interface but I'd need info about the webservice calls.

If you really want to improve the UI, the templates are at https://github.com/vmck/acs-interface/tree/master/interface/templates/interface, it's pretty straightforward to make changes. They use bootstrap 4 and they could use some more consistency e.g. a common base template. The whole user-facing UI of v2.vmchecker is and should be really simple, what would angular give us, besides a bunch of extra complexity?

**Comment by mgax** [comment]
Good enough for now :)
