### ISSUE TITLE
Add quote 

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#65]
Another TA said that he wants to see a quote while waiting for his homework to run on the checker. I think there is a ```quote``` command in the linux command line.

Maybe it is a nice touch to have this (some of them were funny). I do not have a strong opinion regarding this.

**Comment by mgax** [comment]
We can also do a passive-aggressive thing and show random issues that people can work on to improve the platform. Credit goes to @gabriel-v for the idea.

**Comment by gmuraru** [comment]
We can do that :)

**Comment by gmuraru** [comment]
Done.
