### ISSUE TITLE
Students List

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#66]
Currently, you can only see all the submissions, for every homework, in one place. What I'm suggesting is: add a page with each student and his latest submission for each homework or class
Something like the first vmchecker had. It would make grading easier and it would make it easier for students to access their review, too.

**Comment by mgax** [comment]
Fixed by https://github.com/vmck/acs-interface/pull/81 with improvements tracked in https://github.com/vmck/acs-interface/issues/100
