### ISSUE TITLE
TAs privilege should be separated per course

### ISSUE THREAD

**Issue by gmuraru** [vmck/acs-interface#71]
Currently if you add a TA through the admin interface they would have permission to modify any assignment, even if they are not a TA for the other assignment course.

We should have the privilege level added per group/course or per assignment - thought adding per assignment would imply more work from the "admin".

**Comment by mgax** [comment]
@gmuraru this is what you just implemented in https://github.com/vmck/acs-interface/pull/158 no? If so, please close this.

**Comment by gmuraru** [comment]
Yes, it is.
