### ISSUE TITLE
Vagrant - don't clobber "data" folder

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#76]
`vagrant rsync` deletes `data` on the target host, whoops. This only affects the `vagrant-vmck` provider; virtualbox on windows seems to mount a shared folder.

**Comment by gmuraru** [comment]
Is this still a problem?

**Comment by mgax** [comment]
> Is this still a problem?

It's not a problem on virtualbox because it uses synced folders instead of rsync, but if you want to develop using the vmck backend to run your VM, then yes, it's still a problem. But since nobody is using that backend with this repo for now, let's close this issue.
