### ISSUE TITLE
Make makefile errors more descriptive

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#82]
For example, for submission #1121, the output is: 

> make: *** No rule to make target 'build'.  Stop.

Even though the archive has the Makefile file and the needed target for the build rule. This doesn't help the user to find out what's wrong with their source code in order to fix it, having different behaviours on their local host and on the vmchecker platform.

**Comment by Mr-Vinti** [comment]
Also, could @murarugeorgec and I get access to the file system for the PC assignments to be able to manually check these cases, in the meanwhile?

**Comment by mgax** [comment]
> For example, for submission #1121, the output is: `make: *** No rule to make target 'build'. Stop.` Even though the archive has the Makefile file and the needed target for the build rule.

For that particular submission, the archive contains a folder, and the Makefile is inside. It should be at the top level of the archive. I've made an issue to make this visible in the future: https://github.com/vmck/acs-interface/issues/83

> Also, could @murarugeorgec and I get access to the file system for the PC assignments

Ah, but there is no filesystem. The archive is downloaded to a temporary VM that simply runs the checker.

For debugging, we should have a way for the TAs to replicate the checker's flow - [submission/launch.sh from vagrant-vmck](https://github.com/vmck/vagrant-vmck/blob/f64455be29b1bc2b9a9f7e462d8871daa3629dab/submission/launch.sh). Right now you'd need your own [vmck](https://github.com/vmck/vmck/) or access to the production instance.
