### ISSUE TITLE
Show unzip output

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#83]
https://github.com/vmck/acs-interface/issues/82 is caused by the student uploading an archive with a folder inside, instead of having the files at the top level. This is not immediately obvious, a TA has to download the zip and manually inspect it. Let's log the unzip output and show it as part of the checker output.

**Comment by mgax** [comment]
https://github.com/vmck/assignment/blob/pc-01/checker.sh#L4 should be without `-qq`

**Comment by Jokeswar** [comment]
This is up to the assignment's checker script. We can do some gimmicks and add a char field where we save the archive's filenames and then print it out but it's a bit of a hassle. @mgax shall we close this?

**Comment by mgax** [comment]
> shall we close this?

After the checker script is fixed, yes.

**Comment by Jokeswar** [comment]
Done! Now the archive output should be visible.
