### ISSUE TITLE
Output was not being redirected when the server was overloaded

### ISSUE THREAD

**Issue by Mr-Vinti** [vmck/acs-interface#90]
Last night, before the deadline of the PC assignment I noticed certain submissions were finishing, with status Done, but grade None/100. Clicking them, the output field was empty. This happened when there were ~10 submissions running, and for multiple submissions.
Example of submissions like this:
1516, 1515, 1510, 1505

**Comment by Jokeswar** [comment]
Let's retry the POST with the result, every 5 seconds for 5 minutes, so acs-interface has plenty of time to restart.
