### ISSUE TITLE
Cancel an uploaded submission, in case you made a mistake

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#97]
Add the ability to kill an evaulation of the submission. Useful for admins to reduce load on the cluster, and for generous users who upload a new submission and want to free the cluster of the burden of running their previous queued uploads.

Perhaps it would make sense first to create an `Evaluation` model: a `Submission` can have one or more `Evaluation`s, and an `Evaluation` maps 1:1 to a vmck job.

**Comment by Jokeswar** [comment]
Solved by #134 .
