### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#98]
* Log admin actions (perhaps Django already does this for us?)
* Log actions through the UI

Audit logs should answer these questions:
* Who made an action?
* When?
* What was the previous and new state of the resource that they changed?

There should be several ready-made options for us, and if we don't like them, it should be straight-forward to implement for ourselves.

**Comment by Jokeswar** [comment]
https://django-auditlog.readthedocs.io/en/latest/ is a start.

**Comment by mgax** [comment]
Even more options :) https://djangopackages.org/grids/g/model-audit/

**Comment by mgax** [comment]
> https://django-auditlog.readthedocs.io/en/latest/ is a start.

Huh, so they had a cross-site scripting issue a year ago (see issue 189 on their repo) and they have yet to publish the fixed package on PyPI - the last release is from Jan 2018 (https://pypi.org/project/django-auditlog/0.4.5/). And the admin looks like below. Let's try something else.

<img width="822" alt="Screenshot 2019-11-29 at 14 09 50" src="https://user-images.githubusercontent.com/27617/69868275-f0ff5c80-12b1-11ea-9d34-1f6fa529feff.png">

**Comment by Jokeswar** [comment]
@mgax I tried [django reversion](https://github.com/etianen/django-reversion) and [django simple history](https://github.com/treyhunner/django-simple-history), the top apps on https://djangopackages.org/grids/g/model-audit/.

**DJANGO REVERSION**
![Opera Snapshot_2019-12-01_005717_localhost](https://user-images.githubusercontent.com/24795454/69907033-f950b800-13d5-11ea-8d21-3a5a567547ea.png)

**DJANGO SIMPLE HISTORY**
![Opera Snapshot_2019-12-01_005007_localhost](https://user-images.githubusercontent.com/24795454/69907037-0b325b00-13d6-11ea-8ec7-bec329170c6a.png)

Both have the capability of reverting to a previous object stage, but they do not centralize the logs. As a result we have to check every object individually. Now what do you think? With which one do we stick, if we do?

Also as a side note, there is no logging about users or actions. I still think that [django actions logger](https://github.com/shtalinberg/django-actions-logger) might be good enough for `admin actions` despite its downside.
