### ISSUE TITLE
Poll vmck asynchronously instead of as a side effect of browser refresh

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#99]
[this](https://github.com/vmck/acs-interface/blob/master/interface/views.py#L135-L136) is inefficient. We should start a separate background process that polls vmck every few seconds about pending jobs. Create a new [management command](https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/) `sync_vmck` that runs an infinite loop that polls vmck and then sleeps for a few seconds. Run it as a separate task in Nomad.

**Comment by gmuraru** [comment]
Currently, the new command only updates the state in case if it changes from new to running. This is because there is a callback in the ```evaluate``` function from submission.

**Comment by Jokeswar** [comment]
Implemented!
